services:
  - type: web
    name: language-learning-chatbot
    env: python
    buildCommand: apt-get update && apt-get install -y build-essential gfortran libatlas-base-dev && python -m pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false 