services:
  - type: web
    name: language-learning-chatbot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python scripts/init_db.py
    startCommand: gunicorn app:app --workers 4 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1 