services:
  - type: web
    name: language-learning-chatbot
    env: python
    buildCommand: apt-get update && apt-get install -y build-essential gfortran libatlas-base-dev && pip cache purge && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false 